version: "3.7"

services:
  app:
    image: kishikawakatsumi/swift-playground:latest
    container_name: swift-playground
    env_file:
      - .env
    environment:
      HOST_PWD: $PWD/
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - 80:8080
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080",
      ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/Resources/Temp:/app/Resources/Temp
    network_mode: bridge
    links:
      - carbonara
    restart: always

  carbonara:
    image: petersolopov/carbonara
    container_name: carbonara
    ports:
      - 3000:3000
    cap_add:
      - SYS_ADMIN
    network_mode: bridge
    restart: always

  swift-5.4:
    image: kishikawakatsumi/swift:5.4
    container_name: swift-5.4
