name: Build Swift Packages
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Swift Packages
        run: |
          set -ex

          sh scripts/update_installed_swift_packages.sh

          if ! git diff --exit-code --quiet Resources/Views/Package.json
          then
            (cd swift-docker/5.3 && docker build --rm --tag kishikawakatsumi/swift:5.3 . && docker push kishikawakatsumi/swift:5.3)
            (cd swift-docker/5.3.1 && docker build --rm --tag kishikawakatsumi/swift:5.3.1 . && docker push kishikawakatsumi/swift:5.3.1)
            (cd swift-docker/5.3.2 && docker build --rm --tag kishikawakatsumi/swift:5.3.2 . && docker pushkishikawakatsumi/swift:5.3.2)
            (cd swift-docker/5.3.3 && docker build --rm --tag kishikawakatsumi/swift:5.3.3 . && docker push kishikawakatsumi/swift:5.3.3)

            (cd swift-docker/5.4 && docker build --rm --tag kishikawakatsumi/swift:5.4 . && docker push kishikawakatsumi/swift:5.4)
            (cd swift-docker/5.4.1 && docker build --rm --tag kishikawakatsumi/swift:5.4.1 . && docker push kishikawakatsumi/swift:5.4.1)

            BRANCH="$(git rev-parse --abbrev-ref HEAD)"
            if [[ "$BRANCH" == "master" ]]; then
              git config --local user.email ${{ secrets.GIT_USER_EMAIL }}
              git config --local user.name ${{ secrets.GIT_USER_NAME }}

              git add Resources/Views/Package.json
              git commit -m 'Update Package.json'
              git push origin HEAD
            fi
          fi
